/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertmidfixtopostfix;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Khesraw
 */
public class GUIPostfix extends javax.swing.JFrame {

    /**
     * Creates new form GUIPostfix
     */
    public GUIPostfix() {
        initComponents();
        setCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt10 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txtEval = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtInfix = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        txtL1 = new javax.swing.JTextField();
        txtL2 = new javax.swing.JTextField();
        txtL3 = new javax.swing.JTextField();
        txtL4 = new javax.swing.JTextField();
        txtL5 = new javax.swing.JTextField();
        txtL6 = new javax.swing.JTextField();
        txtL7 = new javax.swing.JTextField();
        txtL8 = new javax.swing.JTextField();
        txtL9 = new javax.swing.JTextField();
        txtL10 = new javax.swing.JTextField();
        txtL11 = new javax.swing.JTextField();
        txtL12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 100));

        txt10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtEval.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtEval.setText("35*62/+4- ");

        btnInsert.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnInsert.setText("Evaluate");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Evaluation of Postfix");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        txtInfix.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        btnConvert.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        txtL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtL12.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEval, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtInfix))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(btnConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtL1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtL2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtL3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtL4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtL5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtL6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtL7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtL8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtL9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtL10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtL11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtL12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtInfix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConvert))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInsert))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        txtL3.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
     String s = txtEval.getText();
     char[] postfix = s.toCharArray();
     eval(postfix);
     insertToText(postfix);
     
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        char[] infix = (txtInfix.getText()+" ").toCharArray();
        String postfix = String.valueOf(convert(infix));
        txtEval.setText(postfix);
    }//GEN-LAST:event_btnConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPostfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPostfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPostfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPostfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPostfix().setVisible(true);
            }
        });
    }
    
    public void setColor(int index)
    {
        switch(index)
        {
            case 1:
                txtL1.setForeground(Color.red);
            break;
            case 2:
                txtL2.setForeground(Color.red);
            break;
            case 3:
                txtL3.setForeground(Color.red);
            break;
            case 4:
                txtL4.setForeground(Color.red);
            break;
            case 5:
                txtL5.setForeground(Color.red);
            break;
            case 6:
                txtL6.setForeground(Color.red);
            break;
            case 7:
                txtL7.setForeground(Color.red);
            break;
            case 8:
                txtL8.setForeground(Color.red);
            break;
            case 9:
                txtL9.setForeground(Color.red);
            break;
            case 10:
                txtL10.setForeground(Color.red);
            break;
            case 11:
                txtL11.setForeground(Color.red);
            break;
            case 12:
                txtL12.setForeground(Color.red);
            break;
        }
    }
    
    public void insertToText(char[] postfix)
    {
        for(char i : postfix)
        {
            if(txtL1.getText().equals(""))
            {
                txtL1.setText(i+"");
            }else if(txtL2.getText().equals(""))
            {
                txtL2.setText(i+"");
            }else if(txtL3.getText().equals(""))
            {
                txtL3.setText(i+"");
            }else if(txtL4.getText().equals(""))
            {
                txtL4.setText(i+"");
            }else if(txtL5.getText().equals(""))
            {
                txtL5.setText(i+"");
            }else if(txtL6.getText().equals(""))
            {
                txtL6.setText(i+"");
            }else if(txtL7.getText().equals(""))
            {
                txtL7.setText(i+"");
            }else if(txtL8.getText().equals(""))
            {
                txtL8.setText(i+"");
            }else if(txtL9.getText().equals(""))
            {
                txtL9.setText(i+"");
            }else if(txtL10.getText().equals(""))
            {
                txtL10.setText(i+"");
            }else if(txtL11.getText().equals(""))
            {
                txtL11.setText(i+"");
            }else if(txtL12.getText().equals(""))
            {
                txtL12.setText(i+"");
            }
        }
    }
    
    public char[] convert(char[] in)
    {
        java.util.Stack<Character> st = new java.util.Stack<>();
        st.push('#');
        char[] postfix = new char[in.length+1];
        int i=0;
        int j=0;
        while(in[i] != ' ')
        {
            if(isOperand(in[i]))
            {
                postfix[j++] = in[i++];
            }else
            {
                if(pre(in[i]) > pre(st.peek()))
                {
                    st.push(in[i++]);
                }else
                {
                    postfix[j++] = st.pop();
                }
            }
        }
        while(!st.isEmpty() && st.peek() !='#')
        {
            postfix[j++] = st.pop();
        }
        postfix[j] = ' ';
        
        return postfix;
    }
    
    public void setCenter(JFrame jframe)
    {
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        
        double screenWidth = toolkit.getScreenSize().getWidth();
        double screenHeight = toolkit.getScreenSize().getHeight();
        
        int frameWidth = jframe.getWidth();
        int frameHeight = jframe.getHeight();
        
        double x = (screenWidth-frameWidth)/2;
        double y = (screenHeight-frameHeight)/2;
        
        jframe.setLocation((int)x, (int)y);
      
    }
    
    boolean isOperand(char x)
    {
        if(x=='+' || x=='-' || x=='*' || x=='/')
        {
            return false;
        }else
        {
            return true;
        }
    }
    
    int pre(char x)
    {
        if(x=='+' || x=='-')
        {
            return 1;
        }else if(x=='*' || x=='/')
        {
            return 2;
        }
        return 0;
    }
    
   public void eval(char[] postfix)
   {
       Stack st = new Stack();
       new Thread(new Runnable() {
           @Override
           public void run() {
               int i=0;
               int x1,x2,r=0;
               for(i=0;postfix[i] != ' ';i++)
               {      
                   setColor(i+1);
                    try
                    {
                        Thread.sleep(1050);
                        if(isOperand(postfix[i]))
                        {
                            st.push(postfix[i]-'0');
                            txtInsert((postfix[i]-'0')+"");
                        }else
                        {
                            x2=st.pop();
                            txtDelete();
                            x1=st.pop();
                            txtDelete();
                            switch(postfix[i])
                            {
                                case '+':r=x1+x2;
                                break;
                                case '-':r=x1-x2;
                                break;
                                case '*':r=x1*x2;
                                break;
                                case '/':r=x1/x2;
                                break;
                            }
                            st.push(r);
                            txtInsert(r+"");
                        }
                    }catch(InterruptedException exception)
                    {

                    }
               }
               JOptionPane.showMessageDialog(null,"Result is : " + st.pop(),"Evaluation Result",JOptionPane.INFORMATION_MESSAGE);
           }
       }).start();
       
   } 
    
    public void txtDelete()
    {
        if(txt1.getText().equals(""))
        {
            txt1.setText(null);
        }else if(txt2.getText().equals(""))
        {
            txt1.setText(null);
        }else if(txt3.getText().equals(""))
        {
            txt2.setText(null);
        }else if(txt4.getText().equals(""))
        {
            txt3.setText(null);
        }else if(txt5.getText().equals(""))
        {
            txt4.setText(null);
        }else if(txt6.getText().equals(""))
        {
            txt5.setText(null);
        }else if(txt7.getText().equals(""))
        {
            txt6.setText(null);
        }else if(txt8.getText().equals(""))
        {
            txt7.setText(null);
        }else if(txt9.getText().equals(""))
        {
            txt8.setText(null);
        }else if(txt10.getText().equals(""))
        {
            txt9.setText(null);
        }else
        {
           txt10.setText(null);
        }
    }
    public void txtInsert(String oper)
    {
        if(txt10.getText().equals(""))
        {
            if(txt9.getText().equals(""))
            {
                if(txt8.getText().equals(""))
                {
                    if(txt7.getText().equals(""))
                    {
                        if(txt6.getText().equals(""))
                        {
                            if(txt5.getText().equals(""))
                            {
                                if(txt4.getText().equals(""))
                                {
                                    if(txt3.getText().equals(""))
                                    {
                                        if(txt2.getText().equals(""))
                                        {
                                            if(txt1.getText().equals(""))
                                            {
                                                txt1.setText(oper);
                                            }else
                                            {
                                                txt2.setText(oper);
                                            }
                                        }else
                                        {
                                            txt3.setText(oper);
                                        }
                                    }else
                                    {
                                        txt4.setText(oper);
                                    }
                                }else
                                {
                                    txt5.setText(oper);
                                }
                            }else
                            {
                                txt6.setText(oper);
                            }
                        }else
                        {
                            txt7.setText(oper);
                        }
                    }else
                    {
                        txt8.setText(oper);
                    }
                }else
                {
                    txt9.setText(oper);
                }
            }else
            {
                txt10.setText(oper);
            }
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    private javax.swing.JTextField txtEval;
    private javax.swing.JTextField txtInfix;
    private javax.swing.JTextField txtL1;
    private javax.swing.JTextField txtL10;
    private javax.swing.JTextField txtL11;
    private javax.swing.JTextField txtL12;
    private javax.swing.JTextField txtL2;
    private javax.swing.JTextField txtL3;
    private javax.swing.JTextField txtL4;
    private javax.swing.JTextField txtL5;
    private javax.swing.JTextField txtL6;
    private javax.swing.JTextField txtL7;
    private javax.swing.JTextField txtL8;
    private javax.swing.JTextField txtL9;
    // End of variables declaration//GEN-END:variables
}
